name: On-Demand Publish

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      EXTENSION_TAG:
        description: "branch/tag of the extension to build."
        type: string
        default: main

      RELEASE_TYPE:
        description: "Publish as snapshot or full release"
        type: choice
        options:
          - snapshot
          - release
        default: release

      SKIP_PUBLICATION:
        description: "Skip publication to marketplaces?"
        type: boolean
        default: false

      SKIP_REPOSITORY_PUSH:
        description: "Skip pushing tags/commits back to the repo?"
        type: boolean
        default: false

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      extension_tag: ${{ github.event.inputs.EXTENSION_TAG }}
      force: true
      is_snapshot: ${{ github.event.inputs.RELEASE_TYPE == 'snapshot' }}
      skip_publication: ${{ github.event.inputs.SKIP_PUBLICATION }}
      skip_repository_push: ${{ github.event.inputs.SKIP_REPOSITORY_PUSH }}
    secrets:
      VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      OVSX_MARKETPLACE_TOKEN: ${{ secrets.OVSX_MARKETPLACE_TOKEN }}
